import { MantineProvider } from '@mantine/core'
import { cleanup, fireEvent, render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, describe, expect, it, vi } from 'vitest'
import type { CorrectionContextData, SpinningGateway } from '../integration/contracts'
import { unavailableSpinningGateway } from '../integration/unavailableGateway'
import { CorrectionsWorkspace } from './CorrectionsWorkspace'

Object.defineProperty(window, 'matchMedia', { writable: true, value: () => ({ matches: false, addEventListener: () => {}, removeEventListener: () => {} }) })
afterEach(cleanup)
const data: CorrectionContextData = { context: { section: 'Continuas', businessDate: '2026-09-01', shift: 'A' }, progressContinuityWarning: 'Revise continuidad.', records: [{ family: 'production_discharge', recordId: 'd', section: 'Continuas', businessDate: '2026-09-01', shift: 'A', machine: 'C1', dischargedKg: '10' }, { family: 'progress', recordId: 'p', section: 'Continuas', businessDate: '2026-09-01', shift: 'A', machine: 'C1', outputKg: '12' }, { family: 'process_quality', recordId: 'q', businessDate: '2026-09-01', shift: 'A', profile: 'Perfil', sample: 'Muestra', result: '22' }, { family: 'waste', recordId: 'w', businessDate: '2026-09-01', shift: 'A', area: 'Continuas', wasteKg: '4' }] }
const base = { getIntegrationState: async () => ({ status: 'unavailable' as const, message: 'Not used.', retryable: false }), getSectionContext: async () => ({ status: 'unavailable' as const, message: 'Not used.', retryable: false }), getProductionDischargeCatalog: async () => ({ status: 'unavailable' as const, message: 'Not used.', retryable: false }), getProgressContinuity: async () => ({ status: 'unavailable' as const, message: 'Not used.', retryable: false }), getQualityCaptureCatalog: async () => ({ status: 'unavailable' as const, message: 'Not used.', retryable: false }), getQualityProfiles: async () => ({ status: 'unavailable' as const, message: 'Not used.', retryable: false }), getQualitySampleRecords: async () => ({ status: 'unavailable' as const, message: 'Not used.', retryable: false }) }
const gateway = (overrides = {}): SpinningGateway => ({ ...base, corrections: { readCorrectionContext: vi.fn().mockResolvedValue({ status: 'populated', data }), saveCorrectionContext: vi.fn().mockResolvedValue({ status: 'populated', data }), ...overrides } })
const renderWorkspace = (item = gateway()) => render(<MantineProvider><CorrectionsWorkspace gateway={item} /></MantineProvider>)
async function search(user: ReturnType<typeof userEvent.setup>) { await user.selectOptions(screen.getByLabelText('Sección'), 'Continuas'); fireEvent.change(screen.getByLabelText('Fecha'), { target: { value: '2026-09-01' } }); await user.selectOptions(screen.getByLabelText('Turno'), 'A'); await user.click(screen.getByRole('button', { name: 'Buscar' })) }

describe('CorrectionsWorkspace', () => {
  it('gates context search and renders all applicable grids without legacy controls', async () => { renderWorkspace(); const user = userEvent.setup(); expect((screen.getByRole('button', { name: 'Buscar' }) as HTMLButtonElement).disabled).toBe(true); await search(user); for (const name of ['Descarga de producción', 'Progreso', 'Calidad', 'Desperdicio']) expect(await screen.findByLabelText(name)).toBeTruthy(); expect(screen.queryByText(/Familia del registro|Seleccionar|Revisar registro/)).toBeNull() })
  it('exposes the required section and shift contexts', () => { renderWorkspace(); expect(Array.from((screen.getByLabelText('Sección') as HTMLSelectElement).options, option => option.value)).toEqual(['Preparación', 'Continuas', 'Bobinados', 'Retorcedoras', 'Madejeras', 'Calidad', 'Desperdicio']); expect(Array.from((screen.getByLabelText('Turno') as HTMLSelectElement).options, option => option.value)).toEqual(['', 'A', 'B', 'C']) })
  it('edits a cell and saves the entire context once', async () => { const saveCorrectionContext = vi.fn().mockResolvedValue({ status: 'populated', data }); renderWorkspace(gateway({ saveCorrectionContext })); const user = userEvent.setup(); await search(user); await user.clear(screen.getByLabelText('Progreso Salida')); await user.type(screen.getByLabelText('Progreso Salida'), '10'); await user.type(screen.getByLabelText(/Motivo de la corrección/), ' Ajuste '); await user.click(screen.getByRole('button', { name: 'Guardar' })); expect(saveCorrectionContext).toHaveBeenCalledWith(expect.objectContaining({ reason: 'Ajuste', values: expect.objectContaining({ 'progress:p:outputKg': '10' }) })) })
  it('keeps no fabricated context when unavailable and preserves a failed save draft', async () => { renderWorkspace(unavailableSpinningGateway); const user = userEvent.setup(); await search(user); expect(await screen.findByText(/La integración de Hilatura no está disponible/)).toBeTruthy(); expect(screen.queryByRole('button', { name: 'Guardar' })).toBeNull(); cleanup(); renderWorkspace(gateway({ saveCorrectionContext: vi.fn().mockResolvedValue({ status: 'unavailable', message: 'No disponible.', retryable: false }) })); await search(user); await user.clear(screen.getByLabelText('Progreso Salida')); await user.type(screen.getByLabelText('Progreso Salida'), '10'); await user.type(screen.getByLabelText(/Motivo de la corrección/), 'Motivo'); await user.click(screen.getByRole('button', { name: 'Guardar' })); expect((screen.getByLabelText('Progreso Salida') as HTMLInputElement).value).toBe('10') })
  it('keeps drafts locked until an explicit reread after conflict and shows the warning', async () => { const readCorrectionContext = vi.fn().mockResolvedValue({ status: 'populated', data }); renderWorkspace(gateway({ readCorrectionContext, saveCorrectionContext: vi.fn().mockResolvedValue({ status: 'conflict', message: 'El contexto cambió.' }) })); const user = userEvent.setup(); await search(user); await user.clear(screen.getByLabelText('Progreso Salida')); await user.type(screen.getByLabelText('Progreso Salida'), '10'); await user.type(screen.getByLabelText(/Motivo de la corrección/), 'Motivo'); await user.click(screen.getByRole('button', { name: 'Guardar' })); expect(await screen.findByText('El contexto cambió.')).toBeTruthy(); expect((screen.getByLabelText('Progreso Salida') as HTMLInputElement).value).toBe('10'); expect((screen.getByRole('button', { name: 'Guardar' }) as HTMLButtonElement).disabled).toBe(true); expect(screen.getByText(/Los registros posteriores no se modificarán automáticamente/)).toBeTruthy(); await user.click(screen.getByRole('button', { name: 'Releer contexto' })); expect(readCorrectionContext).toHaveBeenCalledTimes(2); expect((screen.getByRole('button', { name: 'Guardar' }) as HTMLButtonElement).disabled).toBe(false) })
})
