"""Repository protocol for reusable role presets."""
from typing import Protocol
from access.domain.presets import RolePreset
class RolePresetRepository(Protocol):
    def find_by_id(self, preset_id: str) -> RolePreset | None: ...
    def find_by_code(self, preset_code: str) -> RolePreset | None: ...
    def list_all(self, *, limit: int | None = None, offset: int = 0) -> list[RolePreset]: ...
    def count(self) -> int: ...
    def save(self, preset: RolePreset, *, created_by_user_id: str) -> None: ...
